set(TMP_CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH})
set(CMAKE_MODULE_PATH ${ORIGINAL_CMAKE_MODULE_PATH})

find_package(OpenGL)
set(LIBRARY_OPENGL_FOUND 0)
if(${OPENGL_FOUND})	
	set(LIBRARY_OPENGL_LIBRARIES ${OPENGL_gl_LIBRARY} ${OPENGL_glu_LIBRARY})
	set(LIBRARY_OPENGL_FOUND 1)
endif()

set(CMAKE_MODULE_PATH ${TMP_CMAKE_MODULE_PATH})