# przygotowanie do szukania
FIND_INIT(WSDLPULL wsdlpull)

# szukanie
FIND_SHARED(WSDLPULL "wsdlpull" "wsdlpull")

# skopiowanie
FIND_FINISH(WSDLPULL)

if(LIBRARY_WSDLPULL_FOUND)
	if(WIN32)
		FIND_DEPENDENCIES(WSDLPULL LIBRARY_WSDLPULL_FOUND "CURL")
	elseif(UNIX)
		FIND_PREREQUISITES(WSDLPULL LIBRARY_WSDLPULL_FOUND "CURL")
	endif()
endif()