set(TMP_CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH})
set(CMAKE_MODULE_PATH ${ORIGINAL_CMAKE_MODULE_PATH})

find_package(OpenGL)

if(${OPENGL_FOUND})
	set(OPENGL_LIBRARIES)
	list(APPEND OPENGL_LIBRARIES OPENGL_gl_LIBRARY OPENGL_glu_LIBRARY)
endif()

set(CMAKE_MODULE_PATH ${TMP_CMAKE_MODULE_PATH})