# Tapkee
set(TAPKEE_INCLUDE_DIR "${FIND_LIBRARIES_INCLUDE_ROOT}/Tapkee" CACHE PATH "Location(s) of Tapkee headers.")
IF(EXISTS "${TAPKEE_INCLUDE_DIR}" AND IS_DIRECTORY "${TAPKEE_INCLUDE_DIR}")
	set(LIBRARY_TAPKEE_FOUND 1)
else()
	set(LIBRARY_TAPKEE_FOUND 0)
endif()


