# przygotowanie do szukania
FIND_INIT(OPENSSL openssl)

if(WIN32)
	FIND_SHARED(OPENSSL_SSLEAY32 "ssleay32" "ssleay32")
	FIND_SHARED(OPENSSL_LIBEAY32 "libeay32" "libeay32")
elseif(UNIX)
	FIND_SHARED(OPENSSL_LIBSSL "libssl" "libssl")
	FIND_SHARED(OPENSSL_LIBCRYPTO "libcrypto" "libcrypto")
endif()

FIND_FINISH(OPENSSL)

if(WIN32)
	if(LIBRARY_OPENSSL_SSLEAY32_FOUND AND LIBRARY_OPENSSL_LIBEAY32_FOUND)		
		set(LIBRARY_OPENSSL_FOUND 1)
	else()		
		set(LIBRARY_OPENSSL_FOUND 0)
	endif()

elseif(UNIX)
	if(LIBRARY_OPENSSL_LIBSSL_FOUND AND LIBRARY_OPENSSL_LIBCRYPTO_FOUND)
		set(LIBRARY_OPENSSL_FOUND 1)
	else()
		set(LIBRARY_OPENSSL_FOUND 0)
	endif()
endif()

# sprawdzenie
if (LIBRARY_OPENSSL_FOUND)

	if(WIN32)
		FIND_PREREQUISITES(OPENSSL LIBRARY_OPENSSL_FOUND "ZLIB")
	elseif(UNIX)
		FIND_DEPENDENCIES(OPENSSL LIBRARY_OPENSSL_FOUND "ZLIB")
	endif()
	
endif()
