# przygotowanie do szukania
FIND_INIT_CUSTOM_MODULE(CORE core ${EDR_INCLUDE_ROOT} ${EDR_BUILD_ROOT})

# szukanie
FIND_STATIC(CORE "core")

# skopiowanie
FIND_FINISH(CORE)

#FIND_INIT(CORE core)
#FIND_INCLUDE_PLATFORM_HEADERS(CORE core)
#set(CORE_FOUND 1)
#list( APPEND FIND_RESULTS CORE)
#FIND_FINISH(CORE)
